#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
POLARIS_URL="http://localhost:8181"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "Missing ${ENV_FILE}. Run scripts/setup.sh first." >&2
  exit 1
fi

set -a
source "${ENV_FILE}"
set +a

if grep -q '^AIRFLOW_CLIENT_ID=' "${ENV_FILE}"; then
  echo "Polaris application credentials already exist."
  exit 0
fi

echo "Waiting for Polaris..."
for attempt in {1..60}; do
  if curl --fail --silent http://localhost:8182/q/health >/dev/null; then
    break
  fi

  if [[ "${attempt}" -eq 60 ]]; then
    echo "Polaris health check timed out." >&2
    exit 1
  fi

  sleep 2
done

POLARIS_TOKEN="$(
  curl --fail-with-body --silent --show-error \
    --user "${ROOT_CLIENT_ID}:${ROOT_CLIENT_SECRET}" \
    -d 'grant_type=client_credentials' \
    -d 'scope=PRINCIPAL_ROLE:ALL' \
    "${POLARIS_URL}/api/catalog/v1/oauth/tokens" |
    jq -er '.access_token'
)"

auth_headers=(
  -H "Authorization: Bearer ${POLARIS_TOKEN}"
  -H "Polaris-Realm: ${POLARIS_REALM}"
  -H "Content-Type: application/json"
)

echo "Creating Polaris catalog and Airflow permissions..."

CATALOG_PAYLOAD="$(
  jq -n --arg catalog_name "${CATALOG_NAME}" '{
    catalog: {
      name: $catalog_name,
      type: "INTERNAL",
      readOnly: false,
      properties: {
        "default-base-location": "s3://lakehouse-bucket"
      },
      storageConfigInfo: {
        storageType: "S3",
        allowedLocations: ["s3://lakehouse-bucket"],
        endpoint: "http://host.docker.internal:9000",
        endpointInternal: "http://rustfs:9000",
        pathStyleAccess: true,
        region: "us-west-2"
      }
    }
  }'
)"

curl --fail-with-body --silent --show-error \
  -X POST "${POLARIS_URL}/api/management/v1/catalogs" \
  "${auth_headers[@]}" \
  -d "${CATALOG_PAYLOAD}" >/dev/null

PRINCIPAL_RESPONSE="$(
  curl --fail-with-body --silent --show-error \
    -X POST "${POLARIS_URL}/api/management/v1/principals" \
    "${auth_headers[@]}" \
    -d '{"name":"airflow"}'
)"

AIRFLOW_CLIENT_ID="$(jq -er '.credentials.clientId' <<<"${PRINCIPAL_RESPONSE}")"
AIRFLOW_CLIENT_SECRET="$(
  jq -er '.credentials.clientSecret' <<<"${PRINCIPAL_RESPONSE}"
)"

curl --fail-with-body --silent --show-error \
  -X POST "${POLARIS_URL}/api/management/v1/principal-roles" \
  "${auth_headers[@]}" \
  -d '{"name":"airflow_role"}' >/dev/null

  curl --fail-with-body --silent --show-error \
    -X POST \
  "${POLARIS_URL}/api/management/v1/catalogs/${CATALOG_NAME}/catalog-roles" \
  "${auth_headers[@]}" \
  -d '{"name":"lakehouse_role"}' >/dev/null

curl --fail-with-body --silent --show-error \
  -X PUT \
  "${POLARIS_URL}/api/management/v1/principals/airflow/principal-roles" \
  "${auth_headers[@]}" \
  -d '{"principalRole":{"name":"airflow_role"}}' >/dev/null

  curl --fail-with-body --silent --show-error \
    -X PUT \
  "${POLARIS_URL}/api/management/v1/principal-roles/airflow_role/catalog-roles/${CATALOG_NAME}" \
  "${auth_headers[@]}" \
  -d '{"catalogRole":{"name":"lakehouse_role"}}' >/dev/null

  curl --fail-with-body --silent --show-error \
    -X PUT \
  "${POLARIS_URL}/api/management/v1/catalogs/${CATALOG_NAME}/catalog-roles/lakehouse_role/grants" \
  "${auth_headers[@]}" \
  -d '{"type":"catalog","privilege":"CATALOG_MANAGE_CONTENT"}' >/dev/null

cat >>"${ENV_FILE}" <<EOF

# Generated by provision.sh
AIRFLOW_CLIENT_ID=${AIRFLOW_CLIENT_ID}
AIRFLOW_CLIENT_SECRET=${AIRFLOW_CLIENT_SECRET}
EOF

echo "Polaris provisioning complete."
