services:
  postgres:
    image: postgres:18
    container_name: marketplace-postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "marketplace"
    volumes:
      - marketplace_postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: marketplace-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8085:80"

  python:
    build: .
    container_name: marketplace-python
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null

  duckdb:
    image: duckdb/duckdb:latest
    container_name: marketplace-duckdb
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true

volumes:
  marketplace_postgres_data:
  pgadmin_data: