apiVersion: 1

datasources:
  - name: Clickstream Postgres
    uid: clickstream-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: clickstream
    secureJsonData:
      password: clickstream
    jsonData:
      database: clickstream
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
