slice_name: Feature Importance
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  adhoc_filters: []
  datasource: 3__table
  row_limit: 10000
  time_range: No filter
  viz_type: echarts_timeseries_bar
  groupby: []
  metrics:
  - aggregate: MAX
    column:
      column_name: importance
      filterable: true
      groupby: true
      type: DOUBLE
    expressionType: SIMPLE
    label: Importance
    optionName: metric_importance_max
  orientation: horizontal
  show_legend: false
  x_axis: feature
  x_axis_sort: Importance
  x_axis_sort_asc: true
  y_axis_bounds:
  - 0
  - 1
  y_axis_format: .3f
  echart_options: '{"xAxis":{"min":0,"max":1,"interval":0.2,"axisLabel":{"fontSize":16}},"yAxis":{"axisLabel":{"fontSize":16}}}'
query_context: null
cache_timeout: null
uuid: 30000000-0000-0000-0000-000000000005
version: 1.0.0
dataset_uuid: 20000000-0000-0000-0000-000000000003
